version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true

  # 서비스 이름
  tests:
    # 현 디렉토리에 있는 Dockerfile 사용
    build:
      # 도커 이미지를 구성하기 위한 파일들이 있는 위치
      context: .
      # 도커 파일이 어떤 것인지 지정
      dockerfile: Dockerfile.dev
    # 로컬 머신에 있는 파일을 매핑
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    # 테스트 컨테이너가 시작될 때 실행되는 명령어
    command: ["npm", "run", "test"]
